-- AlterTable
ALTER TABLE "addresses" ALTER COLUMN "cityId" DROP DEFAULT,
ALTER COLUMN "districtId" DROP DEFAULT,
ALTER COLUMN "proviceId" DROP DEFAULT;

-- AlterTable
ALTER TABLE "stores" ALTER COLUMN "cityId" DROP DEFAULT,
ALTER COLUMN "districtId" DROP DEFAULT,
ALTER COLUMN "provinceId" DROP DEFAULT;
