export const DATABASE_CREDENTIALS = {
  PORT: process.env.PORT,
  DATABASE_URL: process.env.DATABASE_URL,
};

export const CLOUDINARY_CREDENTIALS = {
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
};

export const CORS_CREDENTIALS = {
  FRONTEND_URL: process.env.FRONTEND_URL,
};
