export const DATABASE_CREDENTIALS = {
  PORT: process.env.PORT,
  DATABASE_URL: process.env.DATABASE_URL,
};

export const CLOUDINARY_CREDENTIALS = {
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
};

export const CORS_CREDENTIALS = {
  FRONTEND_URL: process.env.FRONTEND_URL,
};

export const NODEMAILER_CREDENTIALS = {
  EMAIL_USER: process.env.EMAIL_USER,
  GOOGLE_APP_PASSWORD: process.env.GOOGLE_APP_PASSWORD,
};

export const SERVER_CREDENTIALS = {
  NODE_ENV: process.env.NODE_ENV,
};

export const AUTH_TOKEN = {
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
};

export const PAYMENT_GATEWAY = {
  MERCHANT_ID: process.env.MIDTRANS_MERCHANT_ID,
  CLIENT_KEY: process.env.MIDTRANS_CLIENT_KEY,
  SERVER_KEY: process.env.MIDTRANS_SERVER_KEY,
};

export const SHIPING_PROVIDER = {
  RAJA_ONGKOR_SHIPPING_COST_API_KEY:
    process.env.RAJA_ONGKOR_SHIPPING_COST_API_KEY,
};

export const GOOGLE_OAUTH = {
  CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
};
