-- AlterEnum
ALTER TYPE "TransactionStatus" ADD VALUE 'WAITING_FOR_PAYMENT';

-- AlterTable
ALTER TABLE "addresses" ADD COLUMN     "cityId" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "districtId" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "proviceId" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "stores" ADD COLUMN     "cityId" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "districtId" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "provinceId" INTEGER NOT NULL DEFAULT 1;
